// <auto-generated />
namespace Equipment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class adding_batch_device : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_batch_device));
        
        string IMigrationMetadata.Id
        {
            get { return "201401170808510_adding_batch_device"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
